# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - step: &sonarqube
        name: analyze with hawkman sonarqube server
        script:
           - mvn clean package sonar:sonar -Dsonar.projectKey=n-t-m-e-s -Dsonar.host.url=http://165.22.120.243:9000 -Dsonar.login=6fe927cb875c24260c41660607b8209bc40e1c94
    - step: &build-deploy
        name: build and deploy to docker
        services:
          - docker
        script: # Modify the commands below to build your repository.
          # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
          - export IMAGE=hawkmanlabs/tracker-monitoring-eureka-server
          - export IMAGE_NAME=hawkmanlabs/tracker-monitoring-eureka-server:$BITBUCKET_COMMIT
          - export IMAGE_NAME2=hawkmanlabs/tracker-monitoring-eureka-server:stable

          # build the Docker image (this will use the Dockerfile in the root of the repo)
          - docker build -t $IMAGE_NAME -t $IMAGE_NAME2 .
          # authenticate with the Docker Hub registry
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          # push the new Docker image to the Docker registry
          # testing if stable tag get updated
          - docker push $IMAGE
definitions:
  services:
    docker:
      memory: 2048  #increasing docker memory size
